packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    '@antfu/ni': ^24.1.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    minimist: ^1.2.8
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.1
  inlined:
    '@antfu/utils': ^9.1.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
